### ISSUE TITLE
/etc/iptables/rules.v4 - no such file or directory

### ISSUE THREAD

**Issue by lioramilbaum** [Nordeus/ansible_iptables_raw#5] opened 2016-11-06 20:03 UTC
added the following tasks to fix:

- file: path=/etc/iptables owner=root group=root state=directory

- file: path=/etc/iptables/rules.v4 owner=root group=root state=touch

**Comment by kustodian** [comment] 2016-11-06 20:36
The module should create all the needed directories and files automatically, so it's strange that you have this issues.

Could you please tell me a few more details, since I can't reproduce this bug without it:
* Which distribution are you using on the control and on the managed host?
* Provide an example playbook which causes this issue?
* How do you run the playbook (which remote user are you using, do you use sudo, etc)
* Output of the actual error generated by Ansible

**Comment by lioramilbaum** [comment] 2016-11-07 04:18
control - macOS Sierra
managed host - Ubuntu 12.04 on AWS
remote user - ubuntu
sudo - yes

**Comment by lioramilbaum** [comment] 2016-11-07 04:51
Output of the actual error generated by Ansible

TASK [lmb.jenkins : iptables_raw] **********************************************
failed: [ec2-52-48-141-50.eu-west-1.compute.amazonaws.com] (item=80) => {"failed": true, "item": 80, "msg": "Could not replace file: /tmp/tmpRj_rbT to /etc/iptables/rules.v4: [Errno 2] No such file or directory"}
failed: [ec2-52-48-141-50.eu-west-1.compute.amazonaws.com] (item=8080) => {"failed": true, "item": "8080", "msg": "Could not replace file: /tmp/tmpYbVrvb to /etc/iptables/rules.v4: [Errno 2] No such file or directory"}

**Comment by 5nafu** [comment] 2017-03-28 15:49
Hi,

I can confirm the issue on an upstream debian-jessie (tested with vagrant). Please see the pull request #11 for reproducability.

**Comment by kustodian** [comment] 2017-03-28 15:53
@5nafu I will try it out. Thanks for providing a test playbook.

**Comment by 5nafu** [comment] 2017-03-28 15:55
I just found out, the `/etc/iptables/` directory comes from the package `iptables-persistent`.

Maybe `iptables_raw` should install it?

**Comment by kustodian** [comment] 2017-03-28 15:58
The [documentation](http://blog.nordeus.com/files/libraryblog/articles/managing-iptables-with-ansible/iptables_raw.html) says that you need to have it installed on Debian. Maybe we could install it.

**Comment by 5nafu** [comment] 2017-04-06 10:46
@kustodian , @lioramilbaum : Would you consider moving part of the documentation as fix for this issue?

**Comment by kustodian** [comment] 2017-04-06 11:13
Closing this because it should be resolved with https://github.com/Nordeus/ansible_iptables_raw/pull/12

**Closed by kustodian** 2017-04-06 11:13 UTC
