### ISSUE TITLE
Additional Firewall Rules

### ISSUE THREAD

**Issue by alitvak69** [Nordeus/ansible_iptables_raw#16] opened 2017-11-01 04:55 UTC
I like and appreciate your work.  However, recently, I had to use iptables with a set of the custom rules and make changes to a raw table.  I needed to make stateful  firewall stateless  for some services while keeping the rest of the rules stateful.  This configuration involved inserting rules in front  (-I).  Is there a reason -I is not supported?  Do you have any plans to implement it in the future?

Thank you,

**Comment by kustodian** [comment] 2017-11-01 11:14
I don't understand your use case 100%, if you gave a concrete example, I could try to help you out easier. The module will never support `-I` because it has `weight` which determines in what order the rules will be applied, so inserting isn't needed.

**Comment by alitvak69** [comment] 2017-11-02 01:33
# This example for making DNS lookups stateless 
*raw
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-I PREROUTING -p udp --dport 53 -j NOTRACK
-I PREROUTING -p udp -m udp --sport 53 -j NOTRACK
-I OUTPUT -p udp --dport 53 -j NOTRACK
COMMIT
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-I INPUT -p udp -m udp --dport 53  -s 127.0.0.1   -j ACCEPT
-I INPUT -p udp -m udp --dport 53  -s 4.28.65.138   -j ACCEPT
-I INPUT -p udp -m udp --dport 53 -m iprange --src-range 10.0.0.5-10.0.0.6  -j ACCEPT
-I INPUT -p udp -m udp --dport 53 -m iprange --src-range 10.0.0.9-10.0.0.10  -j ACCEPT
-I INPUT -p udp -m udp --dport 53 -m iprange --src-range 10.0.0.17-10.0.0.18  -j ACCEPT
....
-I OUTPUT -p tcp -m tcp --dport 53  -s 10.0.28.0/22   -j ACCEPT
-I OUTPUT -p tcp -m tcp --dport 53  -s 10.0.72.0/22   -j ACCEPT
-I OUTPUT -p tcp -m tcp --dport 53  -s 10.10.8.0/22   -j ACCEPT
-A INPUT -p udp -m udp --dport 53  -m limit --limit 1000/hour -j LOG  --log-level 6 --log-prefix "DNS --- DENY " --log-tcp-sequence  --log-tcp-options  --log-ip-options
-A INPUT -p udp -m udp --dport 53 -j DROP
-A INPUT   -m state --state ESTABLISHED,RELATED,UNTRACKED -j ACCEPT
-A OUTPUT  -m state --state ESTABLISHED,RELATED,UNTRACKED -j ACCEPT
-A FORWARD -m state --state ESTABLISHED,RELATED,UNTRACKED -j ACCEPT
-N drop_invalid
-A OUTPUT   -m state --state INVALID  -j drop_invalid
-A INPUT    -m state --state INVALID  -j drop_invalid
-A FORWARD  -m state --state INVALID  -j drop_invalid
-A drop_invalid -j LOG --log-level debug --log-prefix "INVALID state -- DENY "
-A drop_invalid -j DROP
-A INPUT -i lo -j ACCEPT
... etc

**Comment by alitvak69** [comment] 2017-11-02 01:36
Not too many examples on using weight.  Do I have to weight all of the rules or I can make some rules with weight 0 and the rest will assume some default weight

**Comment by alitvak69** [comment] 2017-11-02 15:05
I tried weights but in described combination they don't work.   The intended result is to allow DNS requests from specific  addresses and block others.  However when I followed the weight technic anyone still could access my DNS server.  When I loaded iptables file with -I rules, limiting DNS access to certain ports worked as it should.  I can send you my ansible  group_vars and the actual iptables file if you want to take a look at it.

Thank you,

**Comment by kustodian** [comment] 2017-11-02 15:26
Default weight is 40. Smaller the weight, higher the rule is in the list of rules, and the other way around. Also I wouldn't recommend setting weight to 0, because that means you won't be able to put anything in front of them, unless you delete them first. 10 is a good weight for rules which you want to put on top.

Looking at your rules as far as I can see your raw table can be set like this:
```yml
- iptables_raw:
    name: dns_rules
    table: raw
    rules: |
      -A PREROUTING -p udp --dport 53 -j NOTRACK
      -A PREROUTING -p udp -m udp --sport 53 -j NOTRACK
      -A OUTPUT -p udp --dport 53 -j NOTRACK

```
And the filter table (which is the default table) can be set like this:
```yml
- name: DNS rules
  iptables_raw:
    name: dns_rules    # NOTE: rule names are unique per iptables table, that's why we can use `dns_rules` name in both `filter` and `raw` tables.
    table: filter  # this is the default table, so you can remove this param
    weight: 10
    rules: |
      -A INPUT -p udp -m udp --dport 53 -s 127.0.0.1 -j ACCEPT
      -A INPUT -p udp -m udp --dport 53 -s 4.28.65.138 -j ACCEPT
      -A INPUT -p udp -m udp --dport 53 -m iprange --src-range 10.0.0.5-10.0.0.6 -j ACCEPT
      -A INPUT -p udp -m udp --dport 53 -m iprange --src-range 10.0.0.9-10.0.0.10 -j ACCEPT
      -A INPUT -p udp -m udp --dport 53 -m iprange --src-range 10.0.0.17-10.0.0.18 -j ACCEPT
      -A OUTPUT -p tcp -m tcp --dport 53 -s 10.0.28.0/22 -j ACCEPT
      -A OUTPUT -p tcp -m tcp --dport 53 -s 10.0.72.0/22 -j ACCEPT
      -A OUTPUT -p tcp -m tcp --dport 53 -s 10.10.8.0/22 -j ACCEPT
      -A INPUT -p udp -m udp --dport 53 -m limit --limit 1000/hour -j LOG --log-level 6 --log-prefix "DNS --- DENY " --log-tcp-sequence --log-tcp-options --log-ip-options
      -A INPUT -p udp -m udp --dport 53 -j DROP

- name: Other rules
  iptables_raw:
    name: other_rules
    weight: 40  # but this is default, so you can remove this param here
    rules: |
      -A INPUT -m state --state ESTABLISHED,RELATED,UNTRACKED -j ACCEPT
      -A OUTPUT -m state --state ESTABLISHED,RELATED,UNTRACKED -j ACCEPT
      -A FORWARD -m state --state ESTABLISHED,RELATED,UNTRACKED -j ACCEPT
      -N drop_invalid
      -A OUTPUT -m state --state INVALID -j drop_invalid
      -A INPUT -m state --state INVALID -j drop_invalid
      -A FORWARD -m state --state INVALID -j drop_invalid
      -A drop_invalid -j LOG --log-level debug --log-prefix "INVALID state -- DENY "
      -A drop_invalid -j DROP
      -A INPUT -i lo -j ACCEPT
```

This will make sure that the `dns_rules` are always above `other_rules`. I think this is explained nicely in this blog post http://blog.nordeus.com/dev-ops/managing-iptables-with-ansible-the-easy-way.htm.

**Comment by alitvak69** [comment] 2017-11-03 03:44
I gave it a good try but no matter how I position the weights and I followed your advice as well ass the document, it doesn't work.  The rules with weight 40 are loaded in front of other rules.  Command iptables-save shows   exactly that

#####
With weights per your suggested config (dns 10 and other 40)
*raw
:PREROUTING ACCEPT [30032:5509848]
:OUTPUT ACCEPT [44724:6915263]
-A PREROUTING -p udp -m udp --dport 53 -m comment --comment "ansible[iptables_custom_rules_raw_table_rules]" -j NOTRACK
-A PREROUTING -p udp -m udp --sport 53 -m comment --comment "ansible[iptables_custom_rules_raw_table_rules]" -j NOTRACK
-A OUTPUT -p udp -m udp --dport 53 -m comment --comment "ansible[iptables_custom_rules_raw_table_rules]" -j NOTRACK
COMMIT
# Completed on Thu Nov  2 20:35:48 2017
# Generated by iptables-save v1.4.21 on Thu Nov  2 20:35:48 2017
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [15023:1445275]
:Admin_Services - [0:0]
:HA_Services - [0:0]
:IPERF_Services - [0:0]
:NRPE_Services - [0:0]
:RULE_DEFAULT - [0:0]
:RegProxy_Service - [0:0]
:VoIP_Public_Services - [0:0]
:drop_invalid - [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED,UNTRACKED -m comment --comment "ansible[iptables_custom_rules_accept_established]" -j ACCEPT
-A INPUT -m state --state INVALID -m comment --comment "ansible[iptables_custom_rules_drop_invalid]" -j drop_invalid
-A INPUT -i lo -m comment --comment "ansible[iptables_custom_rules_allow_everything_on_loopback]" -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type 8 -m comment --comment "ansible[iptables_custom_rules_allow_ping_reply]" -j ACCEPT
-A INPUT -s 127.0.0.1/32 -p udp -m udp --dport 53 -m comment --comment "ansible[iptables_custom_rules_top_rules]" -j ACCEPT
-A INPUT -s 4.28.65.138/32 -p udp -m udp --dport 53 -m comment --comment "ansible[iptables_custom_rules_top_rules]" -j ACCEPT
-A INPUT -s 8.3.254.0/24 -p udp -m udp --dport 53 -m comment --comment "ansible[iptables_custom_rules_top_rules]" -j ACCEPT
-A INPUT -s 8.29.18.16/32 -p udp -m udp --dport 53 -m comment --comment "ansible[iptables_custom_rules_top_rules]" -j ACCEPT
-A INPUT -s 10.0.0.0/24 -p udp -m udp --dport 53 -m comment --comment "ansible[iptables_custom_rules_top_rules]" -j ACCEPT
-A INPUT -s 10.0.28.0/22 -p udp -m udp --dport 53 -m comment --comment "ansible[iptables_custom_rules_top_rules]" -j ACCEPT
-A INPUT -s 10.0.20.0/22 -p udp -m udp --dport 53 -m comment --comment "ansible[iptables_custom_rules_top_rules]" -j ACCEPT
-A INPUT -s 10.0.72.0/22 -p udp -m udp --dport 53 -m comment --comment "ansible[iptables_custom_rules_top_rules]" -j ACCEPT

#### With my dummy config file with -I
  *filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [6108:1199778]
:Admin_Services - [0:0]
:HA_Services - [0:0]
:IPERF_Services - [0:0]
:NRPE_Services - [0:0]
:RULE_DEFAULT - [0:0]
:RegProxy_Service - [0:0]
:VoIP_Public_Services - [0:0]
:drop_invalid - [0:0]
-A INPUT -s 216.30.100.68/30 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -s 216.30.99.248/30 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -s 216.30.58.134/32 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -s 216.30.48.6/32 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -s 216.30.5.104/30 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -s 216.27.137.114/32 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -s 216.2.167.93/32 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -s 209.152.117.112/28 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -s 208.71.34.46/32 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -s 208.71.34.41/32 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -s 99.33.14.176/29 -p udp -m udp --dport 53 -j ACCEPT
.....
-A INPUT -s 127.0.0.1/32 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -p udp -m udp --dport 53 -m limit --limit 1000/hour -j LOG --log-prefix "DNS --- DENY " --log-level 6 --log-tcp-sequence --log-tcp-options --log-ip-options
-A INPUT -p udp -m udp --dport 53 -j DROP
-A INPUT -m state --state RELATED,ESTABLISHED,UNTRACKED -j ACCEPT
.....
-A drop_invalid -j LOG --log-prefix "INVALID state -- DENY " --log-level 7
-A drop_invalid -j DROP
COMMIT
# Completed on Thu Nov  2 20:41:57 2017
# Generated by iptables-save v1.4.21 on Thu Nov  2 20:41:57 2017
*raw
:PREROUTING ACCEPT [6323:1135721]
:OUTPUT ACCEPT [9327:1440682]
-A PREROUTING -p udp -m udp --sport 53 -j NOTRACK
-A PREROUTING -p udp -m udp --dport 53 -j NOTRACK
-A OUTPUT -p udp -m udp --dport 53 -j NOTRACK
COMMIT

**Comment by alitvak69** [comment] 2017-11-03 04:31
Hmm looks like linux comments translate into some format here, sorry not intentional. I am adding the code I use

```
---
- name: Set default iptables head rules
  iptables_raw:
    name: iptables_default_head
    weight: 8
    keep_unmanaged: '{{ iptables_keep_unmanaged }}'
    state: '{{ (iptables_default_head != "" ) | ternary("present", "absent") }}'
    rules: '{{ iptables_default_head|default(omit) }}'
  tags: iptables

- name: Set default iptables tail rules
  iptables_raw:
    name: iptables_default_tail
    weight: 99
    keep_unmanaged: '{{ iptables_keep_unmanaged }}'
    state: '{{ (iptables_default_tail != "" ) | ternary("present", "absent") }}'
    rules: '{{ iptables_default_tail }}'
  tags: iptables

- name: Set custom iptables rules
  iptables_raw:
    name: 'iptables_custom_rules_{{ item.name }}'
    rules: '{{ item.rules }}'
    state: '{{ item.state }}'
    weight: '{{ item.weight|default(omit) }}'
    table: '{{ item.table|default(omit) }}'
  with_items: '{{ iptables_custom_rules }}'
  tags:
    - iptables
    - iptables_custom

```

I don't load anything in the head in this specific case, I am just  using custom rules and default tail task (to drop).

**Comment by kustodian** [comment] 2017-11-03 20:09
Could you please paste the value of the `iptables_custom_rules` variable, because without that var the code above won't help that much.

**Comment by alitvak69** [comment] 2017-11-04 04:14
Sure, not going to post every rule there but the head tables

```
iptables_custom_rules:
  - name: top_rules
    state: present
    table: filter
    weight: 10
    rules: |
      -A INPUT -p udp -m udp --dport 53  -s 127.0.0.1   -j ACCEPT
      -A INPUT -p udp -m udp --dport 53  -s 4.28.65.138   -j ACCEPT
      -A INPUT -p udp -m udp --dport 53  -s 8.3.254.0/24   -j ACCEPT
      -A INPUT -p udp -m udp --dport 53  -s 8.29.18.16   -j ACCEPT
      -A INPUT -p udp -m udp --dport 53  -s 10.0.0.0/24   -j ACCEPT
      -A INPUT -p udp -m udp --dport 53  -s 10.0.28.0/22  -j ACCEPT
      -A INPUT -p udp -m udp --dport 53  -s 10.0.20.0/22   -j ACCEPT
      -A INPUT -p udp -m udp --dport 53  -s 10.0.72.0/22   -j ACCEPT
...
      -A OUTPUT -p tcp -m tcp --dport 53  -s 8.3.254.0/24   -j ACCEPT
      -A OUTPUT -p tcp -m tcp --dport 53  -s 10.0.20.0/22   -j ACCEPT
      -A OUTPUT -p tcp -m tcp --dport 53  -s 10.0.28.0/22   -j ACCEPT
      -A OUTPUT -p tcp -m tcp --dport 53  -s 10.0.72.0/22   -j ACCEPT
      -A OUTPUT -p tcp -m tcp --dport 53  -s 10.10.8.0/22   -j ACCEPT
      -A INPUT -p udp -m udp --dport 53  -m limit --limit 1000/hour -j LOG  --log-level 6 --log-prefix "DNS --- DENY " --log-tcp-sequence  --log-tcp-options  --log-ip-options
      -A INPUT -p udp -m udp --dport 53 -j DROP
  - name: raw_table_rules
    state: "present"
    table: raw
    rules: |
      -A PREROUTING -p udp --dport 53 -j NOTRACK
      -A PREROUTING -p udp -m udp --sport 53 -j NOTRACK
      -A OUTPUT -p udp --dport 53 -j NOTRACK
  - name: all_filter_rules 
    weight: 40
    table: filter
    state: present
    rules: |
      -A INPUT   -m state --state ESTABLISHED,RELATED,UNTRACKED -j ACCEPT
      -A OUTPUT  -m state --state ESTABLISHED,RELATED,UNTRACKED -j ACCEPT
      -A FORWARD -m state --state ESTABLISHED,RELATED,UNTRACKED -j ACCEPT
      -N drop_invalid
      -A OUTPUT -m state --state INVALID  -j drop_invalid
      -A INPUT  -m state --state INVALID  -j drop_invalid
      -A FORWARD -m state --state INVALID  -j drop_invalid
      -A drop_invalid -j LOG --log-level debug --log-prefix "INVALID state -- DENY "
      -A drop_invalid -j DROP
      -A INPUT -i lo  -j ACCEPT
      -A OUTPUT -o lo -j ACCEPT
      -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
      -N Admin_Services
      -A INPUT -m state --state NEW,ESTABLISHED -m tcp -m multiport -p tcp --dports 22,1311 -j Admin_Services
...
      -N HA_Services
      -A INPUT -m state --state NEW -p udp -m multiport --dports 5404,5405,5406,5407 -j HA_Services
      -A INPUT -m state --state NEW -p tcp -m multiport --dports 2224,3121,21064 -j HA_Services
      -A INPUT -m pkttype --pkt-type multicast -j HA_Services
      -A INPUT -p igmp -j HA_Services
      -A HA_Services -s 8.18.163.0/24 -j ACCEPT
      -A HA_Services -s 38.108.120.0/24 -j ACCEPT
      -A HA_Services -s 8.3.254.0/24 -j ACCEPT

iptables_default_tail: |
  -N RULE_DEFAULT
  -A INPUT -j RULE_DEFAULT
  -A FORWARD -j RULE_DEFAULT
  -A RULE_DEFAULT -m limit --limit 10000/day -j LOG --log-prefix "RULE DEFAULT -- DENY " --log-level 7
  -A RULE_DEFAULT -j DROP

     #end
```

**Comment by kustodian** [comment] 2017-11-09 21:16
I see what the problem is. You probably created some `iptables_custom_rules` rules before, which you set to have a very low weight. Looking at your output those rules are named: `iptables_custom_rules_accept_established`, `iptables_custom_rules_drop_invalid`, because the role you are using adds a prefix `iptables_custom_rules_` to the name of the rule you specify. Just look at the comment of the rules and you'll know which are those rules. What you can do is you can delete them with setting the name of the rules in the `iptables_custom_rules` to absent. For example to delete `iptables_custom_rules_accept_established` you can add the following dictionary into `iptables_custom_rules`:
```
iptables_custom_rules:
  - name: accept_established
    state: absent
```
and just add all other rules which you want to delete. But what you can also do is start clean and just delete all rules with the `iptables_raw` module:
```
- iptables_raw:
    name: '*'
    table: '*'
    state: absent
```
and start clean.

Because the module keeps state, to delete a rule, you have to select it using the name and table, and set state to `absent`, or the rule will never be deleted.

**Comment by kustodian** [comment] 2017-11-09 21:16
Also closing this, because this issue isn't a bug.

**Closed by kustodian** 2017-11-09 21:16 UTC
