### ISSUE TITLE
error with rule

### ISSUE THREAD

**Issue by frank3427** [Nordeus/ansible_iptables_raw#21] opened 2018-02-22 20:17 UTC
- name: open iptable ports for pcs gui
  iptables_raw:
    name: allow_PCS_gui
    rules: '-A RH-Firewall-1-INPUT -p tcp -m tcp --dport 2224 -j ACCEPT'
following error;
fatal: [moc-xcp-21]: FAILED! => {"changed": false, "msg": "There is a problem with the iptables rules:\n\nError message:\niptables-restore: line 2 failed\n\nGenerated rules:\n#######\nfilter\n-A RH-Firewall-1-INPUT -p tcp -m tcp --dport 2224 -j ACCEPT -m comment --comment ansible[allow_PCS_gui]\nCOMMIT\n#####"}
fatal: [moc-xcp-22]: FAILED! => {"changed": false, "msg": "There is a problem with the iptables rules:\n\nError message:\niptables-restore: line 2 failed\n\nGenerated rules:\n#######\nfilter\n-A RH-Firewall-1-INPUT -p tcp -m tcp --dport 2224 -j ACCEPT -m comment --comment ansible[allow_PCS_gui]\nCOMMIT\n#####"}
to retry, use: --limit @/root/moc-xcp1-ha.retry

**Comment by skyiron** [comment] 2018-05-10 03:50
After upgrading Ansible 2.4.2.0 to Ansible 2.5.2.0, I also encountered a similar (if not the same) problem. Working playbooks started throwing errors whenever I used iptables_raw.
I tried upgrading iptables_raw.py from v2.4 to the current version (v2.5), but that made no difference.
In the end, the only thing that fixed the problem was to downgrade to Ansible 2.4.2.0.

I will include my config, roles, etc as a zip attachment.

This is the error that I got.

```
fatal: [35.233.221.212]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "backup": false,
            "ipversion": "4",
            "keep_unmanaged": false,
            "name": "iptables_default_head",
            "rules": "-P INPUT ACCEPT\n-P FORWARD ACCEPT\n-P OUTPUT ACCEPT\n-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT\n-A INPUT -i lo -j ACCEPT\n-A INPUT -p icmp --icmp-type echo-request -j ACCEPT\n-A INPUT -p tcp -m tcp --dport 3795 -j ACCEPT\n-A INPUT -p udp -i eth0 --sport 53 -j ACCEPT\n",
            "state": "present",
            "table": "filter",
            "weight": 10
        }
    },
    "msg": "There is a problem with the iptables rules:\n\nError message:\niptables-restore v1.6.0: iptables-restore: unable to initialize table 'filter'\n\nError occurred at line: 1\nTry `iptables-restore -h' or 'iptables-restore --help' for more information.\n\nGenerated rules:\n#######\n*filter\n-P INPUT ACCEPT\n-P FORWARD ACCEPT\n-P OUTPUT ACCEPT\n-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT -m comment --comment ansible[iptables_default_head]\n-A INPUT -i lo -j ACCEPT -m comment --comment ansible[iptables_default_head]\n-A INPUT -p icmp --icmp-type echo-request -j ACCEPT -m comment --comment ansible[iptables_default_head]\n-A INPUT -p tcp -m tcp --dport 3795 -j ACCEPT -m comment --comment ansible[iptables_default_head]\n-A INPUT -p udp -i eth0 --sport 53 -j ACCEPT -m comment --comment ansible[iptables_default_head]\nCOMMIT\n#####"
}
```
If you need more information, please let me know. I am happy to help.

[config.zip](https://github.com/Nordeus/ansible_iptables_raw/files/1990292/config.zip)

**Comment by kustodian** [comment] 2018-05-10 19:32
@frank3427 sorry for not getting back to you sooner, I manged to miss this. Could you please post the Ansible task that is failing and the error output of Ansible in the code tags, because if you opost them like this, some characters easily get eaten by markdown. From the first look I would say that you are just missing the chain `RH-Firewall-1-INPUT` in your iptables, but without the full task and the full error message it's hard to help.

@skyiron You're issue is completely different and it shouldn't have anything to do with the new version of Ansible. As far as I can see that could only happen if the `iptable_filter` kernel module isn't loaded, but as far as I remember we covered that special case. Will check it out. Could you please try either executing:
```
sudo iptables -nvL
```
or:
```
sudo modprobe iptable_filter
```
any of these to commands should load the `iptable_filter` module and then run the iptables_raw task with Ansible 2.5.2.0. If that works try removing the module with:
```
sudo rmmod iptable_filter
```
and run Ansible again to see if it will fail.

**Comment by kustodian** [comment] 2018-05-10 20:16
@skyiron I just tried testing the module with Ansible 2.5.2 on Ubuntu 16.04.3 and 17.04 and all works fine. I also tried unloading the `iptable_filter` module and it still worked, because the `iptables-restore` command, which the module uses to load rules, loads the module automatically.

Which exact version of Ubuntu 16.04 are you running and does loading the module manually (which I explained in my previous reply) fix the issue for you?

**Comment by skyiron** [comment] 2018-05-11 04:11
@Kustodian Thanks for looking into it and sorry for mixing the 2 issues up.

I've found the cause of the problem. **The error occurs whenever transport=local is set in ansible.cfg**
When I use the default transport option it works. I was only using local because of another issue which has been resolved.

 I've been running Ansible locally on WSL (ubuntu 16.04.4) to provision a remote server running ubuntu 16.04.4.
Executing `sudo iptables -nvL` on WSL resulted in

> iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
> Perhaps iptables or your kernel needs to be upgraded.

and `sudo modprobe iptable_filter` gave

> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-43-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module iptable_filter not found in directory /lib/modules/4.4.0-43-Microsoft

Trying to run and load the module manually results in 

> iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
> Perhaps iptables or your kernel needs to be upgraded.

I don't really understand the transport=local option too well, but I'm guessing WSL is the reason for the problem. I'm happy to drop the issue here, but if you want me to investigate it further I'm happy to do so.

**Comment by kustodian** [comment] 2018-05-12 19:11
You should run the commands I told you on the remote host, not on the host on which you are running Ansible. You can't use `transport=local`, that means that everything will be executed on the host on which you are running Ansible and not on the remote hosts, so that was your problem. Your playbook was being run on the WSL Ubuntu version which doesn't support iptables and I guess you didn't even want to run the playbook local.

May I ask why did you configure `transport`? It's best that you leave it to default (which is `smart`) and Ansible will detect what is the best plugin to use.

**Comment by skyiron** [comment] 2018-05-14 01:01
You're right. I didn't want to run it on WSL. Thank you for explaining it, I had a hard time finding information on it.

Why did I change transport?  I was troubleshooting ssh-agent. I had wanted to authenticate an ssh key with ansible. Unfortunately I had researched myself into a brick wall and changing transport was me desperately grabbing at straws. When it seemingly worked, it led me down a chain of compounding mistakes which ended with me wasting your time (sorry about that).

**Comment by kustodian** [comment] 2018-05-14 08:10
Don't worry all is good. You don't have to explain yourself that you made a mistake, everyone makes mistakes :) I was actually being curious why you changed it. I thought that there might be  something more to it, something I haven't used before.

Anyway I'm closing this for now. @frank3427 if you still have a problem, feel free to create a new issue.

**Closed by kustodian** 2018-05-14 08:10 UTC
